version: "3.8"

services:
  web:
    # build the "release" target from your single Dockerfile
    build:
      context: .
      target: release
    image: myapp-web:latest
    ports:
      - "5001:5000"           # host:container
    env_file: .env
    command: >
      gunicorn webapp.wsgi:app
      --bind 0.0.0.0:5000
    restart: unless-stopped

  cron:
    # same image, same build, but a different start command
    build:
      context: .
      target: release
    image: myapp-cron:latest
    env_file: .env
    command: python -m cronjob.main
    restart: "no"
